### ISSUE TITLE
[Epic 2] Детали вакансии

### ISSUE THREAD

**Issue by Ild0re** [Ild0re/practicum-android-diploma#75]
**Задача 1**
В рамках данной задачи необходимо реализовать:

- [ ] Переход на экран «Детали вакансии» и его вёрстку (в том числе, все действия при нажатии на интерактивные элементы экрана).
- [ ] Выполнение запроса деталей вакансии и его обработку с полной проработкой слоёв Data/Domain/Presentation.
- [ ] Отображение информации о вакансии в соответствии с UI и полученными данными.
- [ ] Рекомендации по коммуникациям:
- [ ] Члены команды, работающие над экраном поиска вакансий и экраном подробного описания вакансий, должны договориться, как именно передавать ID вакансии на экран описания при нажатии на элемент списка результатов поиска.
- [ ] Чтобы работа не блокировалась реализацией экрана поиска вакансий, экран деталей допускается создавать, используя любой из существующих ID вакансии из HeadHunter API (можно попросить наставника о помощи с выбором ID). При необходимости проинформируйте об этом ревьюеров.

**Presentation и UI**

- [ ] Нижняя панель навигации на экране вакансии не отображается.
- [ ] В процессе загрузки информации о вакансии отображается индикатор загрузки.
- [ ] Если при загрузке информации о вакансии нет интернета или произошла ошибка, то должен отображаться соответствующий плейсхолдер.
- [ ] Если загруженный контент не помещается на экране по вертикали, то экран можно проскролить ниже, чтобы увидеть весь контент.
- [ ] Уровень зарплаты отображается согласно полученным данным. Если указана только нижняя граница, то — «от XX», если только верхняя — «до XX», если обе — «от XX до XX», если не указана ни одна из границ — «зарплата не указана».
- [ ] У уровня зарплаты отображается валюта, указанная для этой вакансии.
- [ ] На месте логотипа компании в процессе его загрузки отображается плейсхолдер. Он же отображается, если логотипа нет.
- [ ] Под названием компании должен отображаться её адрес. Если адреса нет, то должно отображаться название региона.
- [ ] Описание вакансии должно отображаться в отформатированном виде согласно HTML-тегам в тексте описания.
- [ ] Если в информации о вакансии нет данных о ключевых навыках, то раздел «Ключевые навыки» не должен отображаться.
- [ ] При нажатии на кнопку «Поделиться» открывается стандартный диалог для отправки ссылки на вакансию с hh.ru в выбранный пользователем мессенджер.

**Data и Domain**

- [ ] Создан Retrofit API interface с suspend-методом для выполнения запроса на получение информации о вакансии.
- [ ] Для запроса информации о вакансии в пакете data.dto созданы классы запроса (Request), ответа (Response) и, если он необходим, класс элементов, составляющий информацию о вакансии.
- [ ] В компоненте для выполнения сетевых запросов получение информации о вакансии выполняется не в главном потоке.
- [ ] Описан и реализован Repository, предоставляющий метод для получения информации о вакансии.
- [ ] Описан и реализован Interactor, обеспечивающий ViewModel связь с Domain-слоем.
- [ ] DTO-классы не используются за пределами Data-слоя. В пакете domain.models созданы соответствующие классы для использования в слое представления.
